### ISSUE TITLE
Icons mess up alignment with dynamic width

### ISSUE THREAD

**Issue by TiZ-EX1** [dunst-project/dunst#254]
![dunst-alignment](https://cloud.githubusercontent.com/assets/4130673/12722302/47e5a97e-c8d2-11e5-9ac3-5307e3f41035.png)

When a notification pops up with an icon and dunst is configured with 0 width, for some reason there is a lot of space to the right of the icon and the text gets pushed off the notification. With static width, it works okay. The command I used to test was `notify-send -i /usr/share/icons/menta/24x24/status/avatar-default.png "test test test test" "test <b>test</b> test <i>test</i>"`

Happens on both git head and 1.1.0.

**Comment by TiZ-EX1** [comment]
Here's the same test with icons on the right.
![dunst-alignment-right](https://cloud.githubusercontent.com/assets/4130673/12723068/d6442954-c8d5-11e5-84cf-4bd1bee70fda.png)

**Comment by TiZ-EX1** [comment]
The issue doesn't appear at all when the text alignment is left. Only with center and right.

**Comment by timofonic** [comment]
Is this project still alive? Are there an active fork or alternative?

**Comment by tsipinakis** [comment]
I cannot reproduce this in HEAD, can you also confirm that this is fixed on your end?

**Comment by TiZ-EX1** [comment]
Sorry for taking so long to get back to you. It's still a problem.
![20170206-120910](https://cloud.githubusercontent.com/assets/4130673/22657889/0909e216-ec66-11e6-8a11-4fac766de492.png)
![20170206-120950](https://cloud.githubusercontent.com/assets/4130673/22657890/090a1d9e-ec66-11e6-9f73-2eac26a96649.png)

**Comment by Eizen** [comment]
I've pushed a fix to the `fixwidth` branch, would you mind testing?

**Comment by TiZ-EX1** [comment]
The fix works, thank you. 👍

**Comment by Eizen** [comment]
Fixed in ec96871
