### ISSUE TITLE
Stringing mouse action together results in action/context not working

### ISSUE THREAD

**Issue by DmitriK** [dunst-project/dunst#778]
I noticed that as of dunst v1.5.0, my middle mouse click context menu stopped working. Specifically, pressing the middle mouse button on a notification results in the notification closing with nothing happening. Keyboard shortcuts for the context menu still work though. Actually got around to debugging it today, and was able to determine the multiple command setting of `mouse_middle_click = do_action, close_current` in the configuration causes the issue. If I remove the `close_current`, the context menu shows up just fine.

To test I've been using this command I that I saw when looking at other issues:
`dunstify --action="replyAction,reply" --action="closeAction,close" "Message received"`

I ran dunst with `dunst -print -verbosity debug` to see if there is any information there. I do see a small difference in the log depending on the configuration, though I'm not sure if it would be much help. I've stripped out the Screen change and ignored XEvents, as well as the common set of events:

`mouse_middle_click = do_action, close_current`:
```
DEBUG: XEvent: processing 'Expose'
DEBUG: XEvent: processing 'ButtonRelease'
DEBUG: RUN
DEBUG: RUN
```
`mouse_middle_click = do_action`:
```
DEBUG: XEvent: processing 'Expose'
DEBUG: XEvent: processing 'ButtonRelease'
DEBUG: RUN
DEBUG: XEvent: processing 'CreateNotify'
DEBUG: RUN
DEBUG: RUN
```

### Installation info

- Version: `1.5.0 (2020-07-23)`
- Install type: `package`
- Distro and version: ` Arch Linux`

**Comment by tsipinakis** [comment]
Reproduced. Thanks for the report.

This is a bad interaction with the multiple action code and how we use a different thread for the context menu. i.e. As soon as the context menu gets launched the main thread continues to close for the notification without waiting for the context menu to finish.

I'm not sure how to cleanly fix this as making the main thread wait means bringing back an older bug where dunst hanged and didn't accept any notifications while the context menu is open. I'll have to think this over.

**Comment by tsipinakis** [comment]
@DmitriK This should be fixed now, please let me know if you find any other issues with it.

**Comment by domenkozar** [comment]
Could we get a release out?

**Comment by domenkozar** [comment]
Actually that patch applied on top of 1.5.0 doesn't fix the issue for me.

**Comment by tsipinakis** [comment]
Hm, this fix appears to have caused more issues than I anticipated. I'll re-open this and revert it for now.

**Comment by tsipinakis** [comment]
@domenkozar Can you try building the following branch, does this fix the issue for you?
https://github.com/tsipinakis/dunst/tree/action-fix

**Comment by domenkozar** [comment]
Yes, that fixes it (I'm not 100% since bluetoothd then crashes, but the popup did show and I managed to confirm).

**Comment by biopsin** [comment]
would it be possible to to keep the do_action,close_current and introduce a do_context,close_current as I like it the way it is now; mouse_left_click = do a action without a context menu and close? 
or am I missing the point completely

**Comment by DmitriK** [comment]
A quick test of the action-fix branch does fix the issue for me, but one thing I'm realizing is that using the config of just `mouse_middle_click = do_action` (which I've been using as a workaround for now) also closes the notification for me, so I'm not sure what else I'm getting by adding the `close_current`. I'm sure I'm missing something, but because of that, I can't really test if `close_current` actually does what it's supposed to.

**Comment by tsipinakis** [comment]
@biopsin I don't understand what you're asking exactly. Currently if there's a `default` action, or only one action/url `do_action` performs that without prompt, otherwise if opens the context menu.

**Comment by biopsin** [comment]
Ah nevermind, thought there for a minute a context would now show up always.. my bad

**Comment by tsipinakis** [comment]
With 8f9e85f122b8b3bc83e5974d23d2558714575209 merged, this can be closed again.

**Comment by lordofscripts** [comment]
Even now in 2024 my Raspberry Pi (updated) comes with dunst v1.5 so I am experiencing this bug. I will try to build the package myself
